language: cpp

compiler:
    - gcc

sudo: required

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_devtools
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh install_r_binary rJava
    - ./travis-tool.sh install_github OHDSI/SqlRender

script:
    - ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

#language: r
#
#warnings_are_errors: true
#
#sudo: required
#
#apt_packages:
#    - libcurl4-openssl-dev
#    - r-cran-rjava
#
#r_binary_packages:
#    - rJava
#
#r_github_packages:
#    - OHDSI/SqlRender
