language: r

warnings_are_errors: true

sudo: required

apt_packages:
    - libcurl4-openssl-dev

r_binary_packages:
    - rJava

r_github_packages:
    - OHDSI/SqlRender

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change
